services:
  auction-api:
    build:
      context: .
      dockerfile: AuctionHouse.WebAPI/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - 'DatabaseConnectionString=Server=<Database host>;Database=AuctionHouse;User Id=<Username>;Password=<Password>;MultipleActiveResultSets=True;'
      - api-key=8ea0cd87-f2aa-4c82-9ba9-5e9508f6e0ad
    working_dir: /app
    restart: unless-stopped

  auction-site:
    build:
      context: .
      dockerfile: AuctionHouse.WebSite/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

      - AuctionApiBaseUrl=http://auction-api:5002
      - api-key=8ea0cd87-f2aa-4c82-9ba9-5e9508f6e0ad
    working_dir: /app
    restart: unless-stopped