services:
  auction-api:
    build:
      context: .
      dockerfile: AuctionHouse.WebAPI/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseConnectionString="Server=mssql.jeppebs.xyz;Database=AuctionHouse;User Id=sa;Password=inserturpass;"
    working_dir: /app
    restart: unless-stopped

  auction-site:
    build:
      context: .
      dockerfile: AuctionHouse.WebSite/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    working_dir: /app
    restart: unless-stopped
